version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn clean
      - mvn install -DskipTests
      - mv target/checkin-0.0.1-SNAPSHOT.jar checkin-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - checkin-0.0.1-SNAPSHOT.jar