version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
    AccessKey: prod/eb-lambda:AWS_ACCESS_KEY_ID
    AccessSecret: prod/eb-lambda:AWS_SECRET_KEY
  parameter-store:
    SNYK_TOKEN: SnykAuth
    SNYK_ORG: SnykPSOrg
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo $SNYK_TOKEN
      - apt-get update
      - apt-get install -y jq
#      - sudo apt-get remove nodejs
#      - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
#      - sudo apt-get install -y nodejs
      - n stable
      - node -v
#      - n latest
      - npm install -g snyk
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
      - snyk config set api=$SNYK_TOKEN
      - export AWS_ACCESS_KEY_ID=$AccessKey
      - export AWS_SECRET_ACCESS_KEY=$AccessKey
      - export AWS_SECRET_KEY=$AccessSecret
      - export AWS_CREDENTIAL_PROFILES_FILE=".aws/credentials"
  post_build:
    commands:
      - mvn test
      - mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then aws codebuild stop-build --id ${CODEBUILD_BUILD_ID} ;fi
      - snyk test --org=$SNYK_ORG --json-file-output=snyk.json
      - cat snyk.json
      - env
      - mvn clean
      - mvn install -DskipTests
      - mv target/checkin-0.0.1-SNAPSHOT.jar checkin-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - checkin-0.0.1-SNAPSHOT.jar